<?php

namespace KnpU\QADayBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    /**
     * @param \DateTime $startDate
     * @param \DateTime $endDate
     * @return EventRepository
     */
    public function findOverlappingWithRange(\DateTime $startDate, \DateTime $endDate)
    {
        /*
        return $this->createQueryBuilder('e')
            ->andWhere('(e.startDate < :endDate AND e.endDate > :startDate) OR (e.endDate > :startDate AND e.startDate < :endDate)')
            ->setParameter('startDate', $startDate)
            ->setParameter('endDate', $endDate)
            ->getQuery()
            ->execute()
        ;
        */

        $qb = $this->createQueryBuilder('e');

        $expr1 = $qb->expr()->andX('e.startDate < :endDate AND e.endDate > :startDate');
        $expr2 = $qb->expr()->andX('e.endDate > :startDate AND e.startDate < :endDate');
        $orExpr = $qb->expr()->orX($expr1, $expr2);

        $qb->andWhere($orExpr)
            ->setParameter('startDate', $startDate)
            ->setParameter('endDate', $endDate)
        ;

        return $qb
            ->getQuery()
            ->execute()
        ;
    }
}
